name: Actualizar TRM Diario
permissions:
  contents: write

on:
  schedule:
    - cron: '05 14 * * *'  # corre cada día a las 14:05 UTC (09:05 Bogotá)
  workflow_dispatch:

jobs:
  update-trm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Obtener y depurar TRM (Frankfurter)
        id: fetch
        run: |
          echo "=== Respuesta cruda Frankfurter ==="
          curl -s "https://api.frankfurter.app/latest?from=USD&to=COP" > response.json
          cat response.json
          # extraemos .rates.COP
          TRM=$(jq -r '.rates.COP' response.json)
          echo "=== TRM extraída: $TRM ==="
          echo "trm=$TRM" >> $GITHUB_OUTPUT

      - name: Generar trm.json
        run: |
          echo '{' > trm.json
          echo "  \"trm\": ${{ steps.fetch.outputs.trm }}," >> trm.json
          echo "  \"updated_at\": \"$(date --utc +'%Y-%m-%dT%H:%M:%SZ')\"" >> trm.json
          echo '}' >> trm.json

      - name: Commit y push de trm.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add trm.json
          git commit -m "Actualiza TRM ${{ steps.fetch.outputs.trm }} ($(date +'%Y-%m-%d'))" || echo "Sin cambios"
          git push
